"use client";
import { useEffect, useMemo, useState } from "react";

type Drill = { concept:string; kind:"fill"|"choice"; code:string; blank?:string; options?:string[]; correct:string; explanation:string; example:string };
const customDrills: Drill[] = [
  { concept:"Two pointers", kind:"fill", code:"function hasPair(nums, target) {\n  let left = 0, right = nums.length - 1;\n  while (left < right) {\n    const sum = nums[left] + nums[right];\n    if (sum === target) return true;\n    if (sum < target) left++;\n    else __BLANK__;\n  }\n  return false;\n}", blank:"Which line moves the right pointer?", correct:"right--", explanation:"The array is sorted. When the sum is too large, moving right leftward is the only move that can lower it.", example:"Two Sum II" },
  { concept:"Sliding window", kind:"choice", code:"for (const char of s) {\n  while (seen.has(char)) {\n    // remove the left edge\n    __BLANK__\n  }\n  seen.add(char);\n}", blank:"Which line removes the left edge?", options:["seen.delete(char)","seen.delete(s[left++])","left++"], correct:"seen.delete(s[left++])", explanation:"Remove the character currently at the left edge, then advance left. Removing char would delete the incoming duplicate instead.", example:"Longest Substring Without Repeating Characters" },
  { concept:"Hash map", kind:"fill", code:"function twoSum(nums, target) {\n  const seen = new Map();\n  for (let i = 0; i < nums.length; i++) {\n    const need = target - nums[i];\n    if (seen.has(need)) return [seen.get(need), i];\n    __BLANK__;\n  }\n}", blank:"What should be stored after checking?", correct:"seen.set(nums[i], i)", explanation:"Store the current number and its index so a later number can find its needed complement.", example:"Two Sum" },
  { concept:"Binary search", kind:"choice", code:"while (left <= right) {\n  const mid = Math.floor((left + right) / 2);\n  if (nums[mid] === target) return mid;\n  if (nums[mid] < target) {\n    __BLANK__\n  }\n}", blank:"How do you discard the left half?", options:["right = mid - 1","left = mid + 1","left = mid"], correct:"left = mid + 1", explanation:"mid is already known to be too small, so the next search begins immediately after it.", example:"Binary Search" },
  { concept:"Stack", kind:"fill", code:"for (const char of s) {\n  if (char === '(') stack.push(char);\n  else {\n    if (stack.length === 0) return false;\n    __BLANK__;\n  }\n}\nreturn stack.length === 0;", blank:"What resolves the most recent open paren?", correct:"stack.pop()", explanation:"A stack is last-in, first-out: the latest unfinished opening parenthesis must be closed first.", example:"Valid Parentheses" },
  { concept:"BFS", kind:"choice", code:"queue.push(start);\nvisited.add(start);\nwhile (queue.length) {\n  const node = queue.shift();\n  for (const neighbor of graph[node]) {\n    if (!visited.has(neighbor)) {\n      __BLANK__\n      queue.push(neighbor);\n    }\n  }\n}", blank:"When should a neighbor be marked visited?", options:["After queue.push(neighbor)","Before queue.push(neighbor)","When it is removed from the queue"], correct:"Before queue.push(neighbor)", explanation:"Marking on enqueue prevents the same node from being added more than once.", example:"Number of Islands" },
];

const extraProblems: Record<string, string[]> = {
  "Arrays & Hashing": ["Contains Duplicate","Valid Anagram","Group Anagrams","Top K Frequent Elements","Encode and Decode Strings","Product of Array Except Self","Valid Sudoku","Longest Consecutive Sequence"],
  "Two Pointers": ["Valid Palindrome","3Sum","Container With Most Water","Trapping Rain Water"],
  "Sliding Window": ["Best Time to Buy and Sell Stock","Longest Repeating Character Replacement","Permutation in String","Minimum Window Substring","Sliding Window Maximum"],
  "Stack": ["Min Stack","Evaluate Reverse Polish Notation","Daily Temperatures","Car Fleet","Largest Rectangle in Histogram"],
  "Binary Search": ["Search a 2D Matrix","Koko Eating Bananas","Find Minimum in Rotated Sorted Array","Search in Rotated Sorted Array","Time Based Key-Value Store","Median of Two Sorted Arrays"],
  "Linked List": ["Reverse Linked List","Merge Two Sorted Lists","Reorder List","Remove Nth Node From End of List","Copy List with Random Pointer","Add Two Numbers","Linked List Cycle","Find the Duplicate Number","LRU Cache","Merge K Sorted Lists","Reverse Nodes in K-Group"],
  "Trees": ["Invert Binary Tree","Maximum Depth of Binary Tree","Diameter of Binary Tree","Balanced Binary Tree","Same Tree","Subtree of Another Tree","Lowest Common Ancestor of a Binary Search Tree","Binary Tree Level Order Traversal","Binary Tree Right Side View","Count Good Nodes in Binary Tree","Validate Binary Search Tree","Kth Smallest Element in a BST","Construct Binary Tree from Preorder and Inorder Traversal","Binary Tree Maximum Path Sum","Serialize and Deserialize Binary Tree"],
  "Heap / Priority Queue": ["Kth Largest Element in a Stream","Last Stone Weight","K Closest Points to Origin","Kth Largest Element in an Array","Task Scheduler","Design Twitter","Find Median from Data Stream"],
  "Backtracking": ["Subsets","Combination Sum","Permutations","Subsets II","Combination Sum II","Word Search","Palindrome Partitioning","Letter Combinations of a Phone Number","N-Queens","Generate Parentheses"],
  "Tries": ["Implement Trie (Prefix Tree)","Design Add and Search Words Data Structure","Word Search II"],
  "Graphs": ["Clone Graph","Max Area of Island","Pacific Atlantic Water Flow","Surrounded Regions","Rotting Oranges","Walls and Gates","Course Schedule","Course Schedule II","Redundant Connection","Number of Connected Components in an Undirected Graph","Graph Valid Tree","Word Ladder"],
  "Advanced Graphs": ["Reconstruct Itinerary","Min Cost to Connect All Points","Network Delay Time","Swim in Rising Water","Alien Dictionary","Cheapest Flights Within K Stops"],
  "1-D Dynamic Programming": ["Climbing Stairs","Min Cost Climbing Stairs","House Robber","House Robber II","Longest Palindromic Substring","Palindromic Substrings","Decode Ways","Coin Change","Maximum Product Subarray","Word Break","Longest Increasing Subsequence","Partition Equal Subset Sum"],
  "2-D Dynamic Programming": ["Unique Paths","Longest Common Subsequence","Best Time to Buy and Sell Stock with Cooldown","Coin Change II","Target Sum","Interleaving String","Longest Increasing Path in a Matrix","Distinct Subsequences","Edit Distance","Burst Balloons","Regular Expression Matching"],
  "Greedy": ["Maximum Subarray","Jump Game","Jump Game II","Gas Station","Hand of Straights","Merge Triplets to Form Target Triplet","Partition Labels","Valid Parenthesis String"],
  "Intervals": ["Insert Interval","Merge Intervals","Non-overlapping Intervals","Meeting Rooms","Meeting Rooms II","Minimum Interval to Include Each Query"],
  "Math & Geometry": ["Rotate Image","Spiral Matrix","Set Matrix Zeroes","Happy Number","Plus One","Pow(x, n)","Multiply Strings","Detect Squares"],
  "Bit Manipulation": ["Single Number","Number of 1 Bits","Counting Bits","Reverse Bits","Missing Number","Sum of Two Integers","Reverse Integer"],
};

const drillTemplates: Record<string, Omit<Drill, "concept" | "example">> = {
  "Arrays & Hashing": {kind:"fill",code:"function solve(nums) {\n  const seen = new Set();\n  for (const n of nums) {\n    if (seen.has(n)) return true;\n    __BLANK__;\n  }\n}",blank:"What makes the lookup available for the next number?",correct:"seen.add(n)",explanation:"Record the current value after checking it, so later values can find it in constant time."},
  "Two Pointers": {kind:"fill",code:"while (left < right) {\n  if (isValid(s[left], s[right])) {\n    left++; right--;\n  } else {\n    __BLANK__;\n  }\n}",blank:"What invariant should guide a pointer move?",correct:"move the pointer",explanation:"Two-pointer solutions maintain an invariant while discarding an impossible part of the search space."},
  "Sliding Window": {kind:"fill",code:"for (let right = 0; right < s.length; right++) {\n  add(s[right]);\n  while (!valid()) {\n    __BLANK__;\n  }\n  best = Math.max(best, right - left + 1);\n}",blank:"What repairs an invalid window?",correct:"remove(s[left++])",explanation:"Expand right, then shrink left only until the window is valid again."},
  "Stack": {kind:"fill",code:"for (const item of input) {\n  while (stack.length && resolves(stack.at(-1), item)) {\n    __BLANK__;\n  }\n  stack.push(item);\n}",blank:"Which stack action resolves the latest pending item?",correct:"stack.pop()",explanation:"A stack resolves work in last-in, first-out order."},
  "Binary Search": {kind:"fill",code:"while (left <= right) {\n  const mid = Math.floor((left + right) / 2);\n  if (works(mid)) right = mid - 1;\n  else __BLANK__;\n}",blank:"How do you advance past an infeasible mid?",correct:"left = mid + 1",explanation:"Binary search discards a half only after the predicate proves it cannot contain the answer."},
};
const defaultTemplate: Omit<Drill, "concept" | "example"> = {kind:"fill",code:"function solve(input) {\n  // Establish the key invariant.\n  __BLANK__;\n  return result;\n}",blank:"What is the next key invariant or state update?",correct:"update the invariant",explanation:"Focus on the state that must stay true after each iteration or recursive call."};
const generatedDrills: Drill[] = Object.entries(extraProblems).flatMap(([category, problems]) => problems.map((concept) => {
  const template = drillTemplates[category] ?? defaultTemplate;
  const options = Array.from(new Set([category, "Hash map", "Two pointers", "Dynamic programming", "BFS / DFS"])).slice(0, 4);
  return {...template, kind:"choice", code:template.code.replace("solve(input)", `solve(input) // ${concept}`), blank:`Which core pattern should lead your first pass on ${concept}?`, options, correct:category, explanation:`This is a ${category} problem. The code prompt is a short pattern-recognition drill; open the walkthrough for the solution structure.`, concept, example:`${category} · ${concept}`};
}));
const drills: Drill[] = [...customDrills, ...generatedDrills];

const walkthroughs: Record<string, { description:string; steps:{ title:string; text:string; code?:string }[] }> = {
  "Two pointers": { description:"Given a sorted array and a target, decide whether any two numbers add up to the target. Return true or false.", steps:[{title:"1. Use the sorted order",text:"The smallest remaining value is on the left and the largest is on the right. Start there—no nested loop needed."},{title:"2. Compare the sum",text:"If the pair hits the target, you are done. If it is too small, keeping the left value can never help.",code:"if (sum < target) left++;"},{title:"3. Shrink the right side when too large",text:"A sum that is too large needs a smaller number, so move the right pointer left. Each pointer only moves one way, making this O(n).",code:"else right--;"}] },
  "Sliding window": { description:"Find the length of the longest substring that has no repeated characters.", steps:[{title:"1. Grow a window",text:"Move right one character at a time and remember which characters are inside the current window."},{title:"2. Repair duplicates",text:"When the incoming character is already present, the window is invalid. Remove characters from the left until it is valid again.",code:"while (seen.has(char)) seen.delete(s[left++]);"},{title:"3. Record the best valid window",text:"After repairing, add the incoming character and compare the window length to your best answer. Both pointers only move forward: O(n)."}] },
  "Hash map": { description:"Return the two indices whose values add up to a target. There is exactly one answer.", steps:[{title:"1. Turn a pair search into a lookup",text:"For each number, calculate the one value it needs to reach the target.",code:"const need = target - nums[i];"},{title:"2. Look behind you",text:"If that needed value is already in the map, its saved index and the current index are the answer."},{title:"3. Save this number for later",text:"Only save after checking—this avoids accidentally using the same element twice.",code:"seen.set(nums[i], i);"}] },
  "Binary search": { description:"Locate a target in a sorted array, or return -1 when it is absent.", steps:[{title:"1. Keep an active interval",text:"left and right describe the only part of the array that could still contain the answer."},{title:"2. Inspect the middle",text:"Compare nums[mid] with target. An exact match ends the search immediately."},{title:"3. Discard a proven-wrong half",text:"When mid is too small, everything through mid is too small. Advance left past it; do the mirror operation when mid is too large.",code:"if (nums[mid] < target) left = mid + 1;\nelse right = mid - 1;"}] },
  "Stack": { description:"Check whether every opening parenthesis in a string is closed in the correct order.", steps:[{title:"1. Push unfinished openings",text:"An opening parenthesis needs a future match, so put it on the stack."},{title:"2. Close the latest opening",text:"A closing parenthesis must match the most recent opening—exactly what a LIFO stack gives you.",code:"const open = stack.pop();"},{title:"3. Check what remains",text:"An empty stack at the end means all openings were matched. Any remaining item means a missing closing parenthesis."}] },
  "BFS": { description:"Explore a graph one distance layer at a time, which gives shortest paths in an unweighted graph.", steps:[{title:"1. Start a queue",text:"Put the starting node in a queue and mark it visited immediately."},{title:"2. Process one node at a time",text:"Remove the front node, then inspect each of its neighbors. The queue naturally keeps nearer nodes ahead of farther nodes."},{title:"3. Mark while enqueuing",text:"Mark each unseen neighbor before adding it. That prevents duplicates from multiple incoming edges.",code:"visited.add(neighbor);\nqueue.push(neighbor);"}] },
};

const roadmap = [
  ["Arrays & Hashing", 9], ["Two Pointers", 5], ["Sliding Window", 6], ["Stack", 6], ["Binary Search", 7], ["Linked List", 11], ["Trees", 15], ["Heap / Priority Queue", 7], ["Backtracking", 10], ["Tries", 3], ["Graphs", 13], ["Advanced Graphs", 6], ["1-D Dynamic Programming", 12], ["2-D Dynamic Programming", 11], ["Greedy", 8], ["Intervals", 6], ["Math & Geometry", 8], ["Bit Manipulation", 7],
] as const;

export default function Home() {
  const [index,setIndex]=useState(0), [input,setInput]=useState(""), [selected,setSelected]=useState(""), [checked,setChecked]=useState(false), [done,setDone]=useState<string[]>([]);
  useEffect(()=>{ const saved=localStorage.getItem("walkcode-done"); if(saved) setDone(JSON.parse(saved)); },[]);
  const drill=drills[index], answer=drill.kind==="fill"?input:selected, correct=answer.trim().toLowerCase()===drill.correct.toLowerCase(), progress=useMemo(()=>Math.round(done.length/drills.length*100),[done]);
  const walkthrough = walkthroughs[drill.concept] ?? {description:`${drill.concept} is part of the ${drill.example.split(" · ")[0]} track. Start by identifying the invariant before writing the full solution.`,steps:[{title:"1. Read the constraints",text:"Name the input size, output, and the work a brute-force solution would repeat."},{title:"2. Choose the pattern",text:`This drill is grouped under ${drill.example.split(" · ")[0]}. Use that pattern to reduce repeated work.`},{title:"3. Trace a tiny example",text:"Walk through two or three values by hand, then turn the invariant into code."}]};
  function next(){setIndex((index+1)%drills.length);setInput("");setSelected("");setChecked(false)}
  function toggleDone(){const nextDone=done.includes(drill.concept)?done.filter(x=>x!==drill.concept):[...done,drill.concept];setDone(nextDone);localStorage.setItem("walkcode-done",JSON.stringify(nextDone))}
  return <main><header><div className="brand"><span>●</span> walkcode</div><div className="streak">{done.length} solved</div></header>
    <section className="hero"><p className="eyebrow">NEETCODE 150 · DOG-WALK DRILL</p><h1>Read the code.<br/><em>Make the move.</em></h1><p>Quick, bite-size reps for the NeetCode 150 roadmap.</p></section>
    <details className="roadmap"><summary><span><b>NeetCode 150 roadmap</b><small>{done.length} quick drills solved · 150 problems ahead</small></span><i>⌄</i></summary><div className="roadmap-body"><p>The full interview-prep path, grouped by pattern. Use the drill below for quick recall, then tackle the matching full problem when you have desk time.</p><div className="topic-grid">{roadmap.map(([topic,count])=><div key={topic}><span>{topic}</span><b>{count}</b></div>)}</div><a href="https://neetcode.io/practice/practice/neetcode150" target="_blank" rel="noreferrer">Open the complete NeetCode 150 list ↗</a></div></details>
    <div className="progress"><i style={{width:`${progress}`+`%`}}/></div>
    <article className="card"><p className="card-label">{drill.kind === "fill" ? "FILL IN THE BLANK" : "CHOOSE THE LINE"}<span>{String(index+1).padStart(2,"0")}/{drills.length}</span></p><h2>{drill.concept}</h2><p className="cue">Problem: <strong>{drill.example}</strong></p>
      <pre><code>{drill.code.split("__BLANK__").map((part,i)=><span key={i}>{part}{i===0&&<mark> ??? </mark>}</span>)}</code></pre><p className="prompt">{drill.blank}</p>
      {drill.kind==="fill" ? <div className="answer-box"><input value={input} onChange={e=>{setInput(e.target.value);setChecked(false)}} onKeyDown={e=>e.key==="Enter"&&answer&&setChecked(true)} placeholder="Type the missing code…" autoCapitalize="off"/><button onClick={()=>setChecked(true)} disabled={!answer}>Check</button></div> : <div className="options">{drill.options!.map(option=><button key={option} className={selected===option?"selected":""} onClick={()=>{setSelected(option);setChecked(false)}}><span>{option}</span></button>)}<button className="check-choice" onClick={()=>setChecked(true)} disabled={!answer}>Check answer</button></div>}
      {checked&&<div className={`result ${correct?"correct":"wrong"}`}><b>{correct?"That’s it.":"Not quite."}</b><p>{drill.explanation}</p>{!correct&&<small>The line is: <code>{drill.correct}</code></small>}</div>}
      <details className="walkthrough"><summary>Want the full walkthrough?</summary><p className="problem-description">{walkthrough.description}</p><div className="steps">{walkthrough.steps.map((step,i)=><section key={step.title}><span>{i+1}</span><div><h3>{step.title}</h3><p>{step.text}</p>{step.code&&<code>{step.code}</code>}</div></section>)}</div></details>
    </article><div className="actions"><button className={`got-it ${done.includes(drill.concept)?"checked":""}`} onClick={toggleDone}>{done.includes(drill.concept)?"✓ Got it":"Mark as got it"}</button><button className="next" onClick={next}>Next drill <span>→</span></button></div><footer><button onClick={()=>{setDone([]);localStorage.removeItem("walkcode-done")}}>Reset progress</button><span>Made for small, steady reps.</span></footer></main>
}
